language: node_js

node_js:
  - "6"

sudo: false


before_script:
  - pwd
  - cd client

cache:
  directories:
    - "client/node_modules"

script:
  - pwd
  - echo "No test framework specific now, yet comming soon. \n Run webpack instead."
  - npm i
  - npm i webpack -g
  - npm run pack

after_success:
  - echo "Build success!"
